### ISSUE TITLE
[DEV] Investigate what effects the price of multisafe creation

### ISSUE THREAD

**Issue by 4iresan** [multi-safe/ui.multisafe#18]

**Comment by shadowray** [comment]
As mentioned in NEAR Protocol Concepts page:

> **_TRANSACTION_**: A transaction is the smallest unit of work that can be assigned to the network. Work in this case means compute (ie. executing a function) or storage (ie. reading / writing data).

What does it mean? When we create a multsafe, it is managed to be a transaction as Money Transfer or different operation tha we do based on NEAR Protocol blockchain. Accordingly, each transaction requires `Gas` and `Transaction Fee`. 

These components are interlinked. _Gas_ is "time fuel" and very tiny. `1 ms ≈ 1 TGas ≈ 1/1000 NEAR`. 

So the cost of multisafe creation depends on complexity of te operation. As I worked this out on `testnet`, this one is heavy (of what I have experienced)
