### ISSUE TITLE
Account ID pattern improvements

### ISSUE THREAD

**Issue by mikedotexe** [multi-safe/ui.multisafe#71]
I believe regex patterns need to updated to include valid [subaccounts](https://docs.near.org/docs/concepts/account#subaccounts).

https://github.com/multi-safe/ui.multisafe/blob/a9d9bc2fc1fd1c6c5c62ada1c01f7ea6484a214a/src/utils/validation/CreateMultisafePage.js#L24

and potentially:

https://github.com/multi-safe/ui.multisafe/blob/a9d9bc2fc1fd1c6c5c62ada1c01f7ea6484a214a/src/utils/validation/SendFundsModal.js#L14

Note the error here that should be valid:
![Screen Shot 2021-10-13 at 3 52 44 PM](https://user-images.githubusercontent.com/1042667/137224114-a5b11f34-369c-4bd8-b911-0bd955c7cc28.png)

I also noticed it is failing on legitimate account names:

I'm looking in the Wallet code, and this seems to be the more loose regex they're using. At some point in the future, people will be able to have the account `mike` on mainnet without it having to be `mike.near`.

https://github.com/near/near-wallet/blob/072515eb8c2eedb75a89ddbdc94d7c86ef3c276a/packages/frontend/src/components/send/components/InputAccountId.js#L131

Note this valid account:
![Screen Shot 2021-10-13 at 4 16 09 PM](https://user-images.githubusercontent.com/1042667/137225371-f2a50df0-0817-4863-a2fd-587594071a40.png)

**Comment by eclipseeer** [comment]
Fixed
