### ISSUE TITLE
Pending outgoing transaction displays "Completed" in History

### ISSUE THREAD

**Issue by mikedotexe** [multi-safe/ui.multisafe#73]
Seems like the status of "Completed" shown here should actually be "Pending" or "Pending approvals" or something. This is when I've sent one outgoing transaction and signed it with one account.

![multisafe01](https://user-images.githubusercontent.com/1042667/137226636-6cf499cc-2d12-4f3f-a009-ed12d3e510e4.gif)

**Comment by eclipseeer** [comment]
Fixed
![image](https://user-images.githubusercontent.com/18114189/140695373-03fef65d-7313-4e3d-bf3b-40a1d7c322cf.png)
