### ISSUE TITLE
History tab no longer rendering

### ISSUE THREAD

**Issue by mikedotexe** [multi-safe/ui.multisafe#74]
This seems like a new bug, where the History tab shows React errors when I try to navigate to it:

>Uncaught (in promise) Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20Cannot%20convert%20undefined%20or%20null%20to%20object for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

The URL shown in my browser in this video is:
https://multisafe-bounty-testnet.netlify.app/multisafe/qamike01.dev-1612259671980-4872321/history

https://user-images.githubusercontent.com/1042667/139737960-ff2bc297-a740-428a-b61e-b956b04641f6.mp4

**Comment by eclipseeer** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/18114189/139800615-ceb18dea-bad9-4c31-a598-0c21756cf649.png)
